/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.User;

/**
 *
 * @author anmolvalecha
 */
public class FormPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    private User newUser;
    
    private JPanel bottomPanel;
   
    public FormPanel(JPanel inputPanel) {
        initComponents();
        this.bottomPanel = inputPanel;
    }

    //public ImageIcon getSelectedImage() {
     //   return selectedImage != null ? selectedImage : null;
    //}
    
    /*private void handleImageSelection() {
        JFileChooser fileChooser = new JFileChooser();
        

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            
            selectedImage = new ImageIcon(selectedFile.getAbsolutePath());
            
        }
    }
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        titlelLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        ageComboBox = new javax.swing.JComboBox<>();
        emailTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        messageSrcollPane = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        genderLabel = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        preferNotToSayRadioButton = new javax.swing.JRadioButton();
        pictureButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        uploadImageLabel = new javax.swing.JLabel();
        patientTypeLabel = new javax.swing.JLabel();
        patientTypeComboBox = new javax.swing.JComboBox<>();

        mainPanel.setBackground(new java.awt.Color(255, 204, 204));
        mainPanel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N

        titlelLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        titlelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelLabel.setText("Patient Form ");

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        ageLabel.setText("Age");

        emailLabel.setText("Email Address");

        ageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", " " }));
        ageComboBox.setSelectedIndex(-1);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        messageLabel.setText("Message");

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        messageSrcollPane.setViewportView(messageTextArea);

        genderLabel.setText("Gender");

        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setText("Male");
        maleRadioButton.setActionCommand("Male User");

        genderButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setText("Female");
        femaleRadioButton.setActionCommand("Female User");

        genderButtonGroup.add(preferNotToSayRadioButton);
        preferNotToSayRadioButton.setText("Prefer not to say");
        preferNotToSayRadioButton.setActionCommand("User prefers not to say ");

        pictureButton.setText("Upload Picture");
        pictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pictureButtonActionPerformed(evt);
            }
        });

        imageLabel.setText("Image");

        uploadImageLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        uploadImageLabel.setText("path");

        patientTypeLabel.setText("Patient Type");

        patientTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Dental", "Vision", "Pregnant", "Other", " " }));
        patientTypeComboBox.setSelectedIndex(-1);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addComponent(ageLabel)
                    .addComponent(emailLabel)
                    .addComponent(messageLabel))
                .addGap(30, 30, 30)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField)
                    .addComponent(messageSrcollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(firstNameTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNameLabel)
                    .addComponent(genderLabel)
                    .addComponent(patientTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageLabel))
                .addGap(41, 41, 41)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preferNotToSayRadioButton)
                            .addComponent(maleRadioButton)
                            .addComponent(femaleRadioButton)
                            .addComponent(patientTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pictureButton)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(uploadImageLabel)))))
                .addGap(453, 453, 453))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(588, 588, 588)
                        .addComponent(submitButton))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(titlelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titlelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel))
                .addGap(35, 35, 35)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(ageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel)
                    .addComponent(maleRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femaleRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preferNotToSayRadioButton)
                .addGap(16, 16, 16)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(patientTypeLabel)
                        .addComponent(patientTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageLabel)
                    .addComponent(messageSrcollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imageLabel)
                            .addComponent(pictureButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uploadImageLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(168, 168, 168))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        newUser = new User();
         
        newUser.setfName(firstNameTextField.getText());
        if (!newUser.getfName().matches("^[a-zA-Z]+$")) {
           JOptionPane.showMessageDialog(null, "Please enter a valid first name", "Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
       
        newUser.setlName(lastNameTextField.getText());
        if (!newUser.getlName().matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid last name", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Object selectedAge = ageComboBox.getSelectedItem();
        if (selectedAge == null) {
            JOptionPane.showMessageDialog(null, "Please select an age", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        newUser.setAge(selectedAge.toString());

        // String gender = selectedGender.toString();

        Object selectedGender = genderButtonGroup.getSelection();
        if (selectedGender == null)    {
            JOptionPane.showMessageDialog(null, "Please select a gender", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Object selectedPatientType = patientTypeComboBox.getSelectedItem();
        if (selectedPatientType == null){
            JOptionPane.showMessageDialog(null, "Please select a patient type", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        newUser.setPatientType(selectedPatientType.toString());
        
        newUser.setGender(genderButtonGroup.getSelection().getActionCommand());
        if (maleRadioButton.isSelected()) {
            newUser.setGender("Male");
        }
        else if (femaleRadioButton.isSelected()) {
            newUser.setGender("Female");
        }
        else if (preferNotToSayRadioButton.isSelected()) {
            newUser.setGender("Prefer not to say");
        }
        //else    {
          //  gender = "Unknown";
        //}
        
        newUser.setEmail(emailTextField.getText());
        if (newUser.getEmail().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter an email address", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        if (!newUser.getEmail().matches(emailRegex))   {
            JOptionPane.showMessageDialog(null, "Please enter a valid email address", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        newUser.setMessage(messageTextArea.getText());
        if (newUser.getMessage().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a message", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further processing
        }

        if (newUser.getMessage().length() > 500) {
            JOptionPane.showMessageDialog(null, "Message is too long", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        ImageIcon imageIcon = new ImageIcon("path/to/your/image.jpg");
        newUser.setPic(imageIcon);
        uploadImageLabel.setIcon(newUser.getPic());
        
        //System.out.println(fName+" "+ lName+ " "+ age +" "+ email +" " + message + " ");
        //JOptionPane.showMessageDialog(this, fName+"  "+ lName+ " "+ age +" "+ email +" " + message + " ", "Customer Information", HEIGHT);
        /*JOptionPane.showMessageDialog(
            this,
            "CUSTOMER INFORMATION" + "\n" + "\n" +
            "First Name: " + fName + "\n" +
            "Last Name: " + lName + "\n" +
            "Age: " + age + "\n" +
            "Gender: " + gender + "\n" +
            "Email: " + email + "\n" +
            "Message: " + message,
            "Form Submitted",
            JOptionPane.INFORMATION_MESSAGE
        );
        */
        JOptionPane.showMessageDialog(
            this,
            "Form has been submitted.",
            "Submission Successful",
            JOptionPane.INFORMATION_MESSAGE
        );
        
       ViewPanel newViewPanel = new ViewPanel(newUser);
        bottomPanel.add(newViewPanel);
       CardLayout layout = (CardLayout)bottomPanel.getLayout();
        layout.next(bottomPanel);
      
    
    }//GEN-LAST:event_submitButtonActionPerformed
    private ImageIcon Icon;
    private String path;
    
    private void pictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pictureButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg","jpeg","png");
        fileChooser.setFileFilter(filter);
        
        int returnValue = fileChooser.showOpenDialog(null);
        
        if(returnValue ==JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            if(isImageFile(selectedFile)){
                Icon = new ImageIcon(selectedFile.getAbsolutePath());
                path = selectedFile.getAbsolutePath();
                JOptionPane.showMessageDialog(this, "Selected Image", "Image is Upploaded",JOptionPane.INFORMATION_MESSAGE, Icon);
            }else{
                JOptionPane.showMessageDialog(this, "Please select file properly", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
      
    }//GEN-LAST:event_pictureButtonActionPerformed
    private boolean isImageFile (File file){
        String fileName = file.getName().toLowerCase();
        return fileName.endsWith(".jpg") || fileName.endsWith(".jpeg") || fileName.endsWith(".png");
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ageComboBox;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JScrollPane messageSrcollPane;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JComboBox<String> patientTypeComboBox;
    private javax.swing.JLabel patientTypeLabel;
    private javax.swing.JButton pictureButton;
    private javax.swing.JRadioButton preferNotToSayRadioButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titlelLabel;
    private javax.swing.JLabel uploadImageLabel;
    // End of variables declaration//GEN-END:variables
}
